// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gruppe9.Migrations.Eksemplar
{
    [DbContext(typeof(EksemplarContext))]
    partial class EksemplarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Gruppe9.Models.Bok", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<int>("AntallSider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Forfatter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Forlag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tittel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UtgittÅr")
                        .HasColumnType("INTEGER");

                    b.HasKey("ISBN");

                    b.ToTable("Bok");
                });

            modelBuilder.Entity("Gruppe9.Models.Eksemplar", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<int>("EksNr")
                        .HasColumnType("INTEGER");

                    b.HasKey("ISBN", "EksNr");

                    b.ToTable("Eksemplar");
                });

            modelBuilder.Entity("Gruppe9.Models.Eksemplar", b =>
                {
                    b.HasOne("Gruppe9.Models.Bok", "Bok")
                        .WithMany("Eksemplar")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bok");
                });

            modelBuilder.Entity("Gruppe9.Models.Bok", b =>
                {
                    b.Navigation("Eksemplar");
                });
#pragma warning restore 612, 618
        }
    }
}
